---
- name: Create a Virtual Machine in vSphere
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars_create_vm.yaml  # Include the variable file
  tasks:
    - name: Create or Manage VM
      community.vmware.vmware_content_deploy_template:
        hostname: "{{ provision_vm_hostname }}"
        username: "{{ provision_vm_username }}"
        password: "{{ provision_vm_password }}"
        validate_certs: "{{ provision_vm_validate_certs }}"
        datacenter: "{{ provision_vm_datacenter }}"
        cluster: "{{ provision_vm_cluster }}"
        folder: "{{ provision_vm_folder }}"
        datastore: "{{ provision_vm_datastore }}"
        template: "{{ provision_vm_template }}"
        name: "{{ provision_vm_name }}"
        state: poweredon
      delegate_to: localhost

