---
- name: vm disk Playbook
  hosts: pflex_vm
  become: false
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: /home/admin/Ansible/Playbooks/vars_diskadd.yaml
    
  tasks:
    - name: add disk to vm
      vmware_guest_disk:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        name: "{{ vm_name }}"
        disk:
          - size_gb: "{{ vm_disk_gb }}"
            type: "{{ vm_disk_type }}"
            datastore: "{{ vm_disk_datastore }}"
            state: present
            scsi_controller: "{{ vm_disk_scsi_controller }}"
            unit_number: "{{ vm_disk_scsi_unit }}"
            scsi_type: "{{ vm_disk_scsi_type }}"
            disk_mode: "{{ vm_disk_mode }}"

    - name: Force SCSI subsystem to rescan for new disk
      command: echo "- - -" | tee /sys/class/scsi_host/host*/scan
      become: true
      register: scan_output
