---
- name: Install and start NGINX
  hosts: plex_vm
  become: yes
  tasks:
    - name: Ensure NGINX is installed
      apt:
        name: nginx
        state: present
        update_cache: yes
      
    - name: Ensure NGINX is started and enabled
      systemd:
        name: nginx
        state: started
        enabled: yes

