---
- name: Apply Security Patches on RHEL Servers
  hosts: server
  become: true
  tasks:

    - name: Update only security patches
      command: dnf update --security -y
      register: update_result
      failed_when: "'No packages marked for update' in update_result.stdout"
    

