---
- name: Rollback changes 
  hosts: rhel8
  become: yes
  tasks:
    - name: Set SELinux to permissive mode
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=permissive'
    
    - name: Set SELinux to permissive immediately
      command: setenforce 0
      ignore_errors: yes

    - name: Ensure firewalld is stopped and disabled
      service:
        name: firewalld
        state: stopped
        enabled: no
    
    - name: Restore SSH configuration (PermitRootLogin yes, Protocol 1, PasswordAuthentication yes)
      block:
        - name: Allow root login in SSH
          lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^PermitRootLogin'
            line: 'PermitRootLogin yes'
          notify: Restart SSH  # Notify the handler
        
        - name: Set SSH protocol to 1
          lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^Protocol'
            line: 'Protocol 1'
        
        - name: Enable password authentication in SSH
          lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^PasswordAuthentication'
            line: 'PasswordAuthentication yes'
          notify: Restart SSH  # Notify the handler

    - name: Restore file permissions on /etc/passwd
      file:
        path: /etc/passwd
        owner: root
        group: root
        mode: '0644'

    - name: Restore file permissions on /etc/shadow
      file:
        path: /etc/shadow
        owner: root
        group: root
        mode: '0600'

    - name: Restore default shell for system accounts
      user:
        name: "{{ item }}"
        shell: /bin/bash
      loop:
        - bin
        - daemon
        - adm
        - lp
        - sync
        - shutdown
        - halt
        - mail
        - operator
        - games
        - ftp
        - nobody
        - dbus
        - systemd-timesync
        - systemd-network
        - systemd-resolve
        - systemd-journal-remote
        - systemd-journal-gateway
        - systemd-cgls
        - systemd-cgtop
        - systemd-tty-ask-password-agent

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted
