---
- name: Rollback changes made by the previous playbook
  hosts: rhel8
  become: yes
  tasks:
    - name: Ensure PasswordAuthentication is enabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'

    - name: Set SELinux to permissive mode
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=permissive'
    
    - name: Set SELinux to permissive immediately
      command: setenforce 0
      ignore_errors: yes

    - name: Ensure firewalld is stopped and disabled
      service:
        name: firewalld
        state: stopped
        enabled: no
    
    - name: Restore SSH configuration (PermitRootLogin yes, Protocol 1, PasswordAuthentication yes)
      block:
        - name: Allow root login in SSH
          lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^PermitRootLogin'
            line: 'PermitRootLogin yes'
        
        - name: Set SSH protocol to 1
          lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^Protocol'
            line: 'Protocol 1'
        
        - name: Restart SSH service
          service:
            name: sshd
            state: restarted

    - name: Restore file permissions on /etc/passwd
      file:
        path: /etc/passwd
        owner: root
        group: root
        mode: '0644'

    - name: Restore file permissions on /etc/shadow
      file:
        path: /etc/shadow
        owner: root
        group: root
        mode: '0600'

    - name: Restore default shell for system accounts
      user:
        name: "{{ item }}"
        shell: /bin/bash
      loop:
        - bin
        - daemon
        - adm
        - lp
        - sync
        - shutdown
        - halt
        - mail
        - operator
        - games
        - ftp
        - nobody
        - dbus
        - systemd-timesync
        - systemd-network
        - systemd-resolve
        - systemd-journal-remote
        - systemd-journal-gateway
        - systemd-cgls
        - systemd-cgtop
        - systemd-tty-ask-password-agent

    - name: Ensure SSH root login is disabled (if it was previously enabled)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Restart SSH

    - name: Ensure SSH protocol is set to 2 (if it was set to 1)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Protocol'
        line: 'Protocol 2'
      notify: Restart SSH

    - name: Ensure firewall is running
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Ensure SSH idle timeout is configured
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^ClientAliveInterval'
        line: 'ClientAliveInterval 300'
      notify: Restart SSH

    - name: Ensure SSH login grace time is set to a low value
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^LoginGraceTime'
        line: 'LoginGraceTime 1m'
      notify: Restart SSH
