---
- name: Install and configure NGINX
  hosts: all
  become: yes
  tasks:
    - name: Install NGINX (default stream)
      dnf:
        name: nginx
        state: present

    - name: Enable NGINX module stream (if needed)
      command: dnf module enable nginx:1.22 -y
      when: ansible_facts.packages.get('nginx') is not defined

    - name: Open HTTP and HTTPS ports in the firewall
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - http
        - https

    - name: Reload firewalld to apply changes
      firewalld:
        state: reloaded

    - name: Enable NGINX service to start on boot
      systemd:
        name: nginx
        enabled: yes
        state: started
